language: python
python:
  - 2.7
  - 3.5
  - 3.6
pytorch:
  - 0.1
  - 0.1.6
  - 0.1.7
  - 0.1.8
  - 0.1.9
  - 0.1.10
  - 0.1.11
  - 0.1.12
  - 0.2.0
  - 0.3.0
  - 0.3.1
  - 0.4.0
matrix:
  exclude:
    - python: 3.6
      pytorch: 0.1
    - python: 3.6
      pytorch: 0.1.6
install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  - conda create -q -n pytorch python=$TRAVIS_PYTHON_VERSION
  - source activate pytorch
  - conda install -y pytorch=$pytorch -c soumith
  - conda install -y torchvision-cpu -c pytorch
  - conda install -y numpy matplotlib tqdm pillow scikit-learn
  - conda install -y pytest

script:
  - pytest test/
